# Replace ls with exa
alias ls='eza -al --color=always --group-directories-first --icons'     # preferred listing
alias la='eza -a --color=always --group-directories-first --icons'      # all files and dirs
alias ll='eza -l --color=always --group-directories-first --icons'      # long format
alias lt='eza -aT --color=always --group-directories-first --icons'     # tree listing
alias l.='eza -ald --color=always --group-directories-first --icons .*' # show only dotfiles

# Replace cat with bat
alias cat='bat --style header --style snip --style changes --style header'

# Replace cd with z
alias cd='z'

# kubectl 
alias k=kubectl

# Common use
alias tarnow='tar -acf '
alias untar='tar -zxvf '
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias grep='ugrep --color=auto'
alias fgrep='ugrep -F --color=auto'
alias egrep='ugrep -E --color=auto'

# oj and acc
alias ojtg="oj t -c \"go run main.go\" -d tests -N"
alias acs="acc s"
