{
  imports = [
    ../browser/firefox
    ../browser/chrome
    ../communication
    ../editor/neovim
    ../editor/vscode
    ../fonts
    ../git
    ../home-manager
    ../latex
    ../megasync
    ../openssh
    ../programinglang/go
    ../rdp
    ../shell/bash
    ../utilities
    ../xdg
  ];
}
